name: Build and Push Podman Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Authenticate with GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io --username "${{ github.actor }}" --password-stdin

      - name: Build Docker Image with Podman
        run: |
          podman build -t ghcr.io/${{ github.actor }}/pushover-webhook:latest .

      - name: Push Docker Image to GitHub Container Registry
        run: |
          podman push ghcr.io/${{ github.actor }}/pushover-webhook:latest
