name: Notify Discord on Build Completion

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "simulate work"; sleep 1

  discord:
    name: Send Discord Notification
    needs: publish
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Post to Discord via curl
        run: |
          # Set your webhook here or use: WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK }}"
          WEBHOOK_URL="https://discord.com/api/webhooks/1425399520279134249/_tpbIAr_l4c1TVyTTIfCxTt_4RHeYJP8BNEf6Fj9mrG-XREPrThEzPn1-9g4DWiCqtUK"

          TITLE="${{ github.workflow }}"
          STATUS="${{ needs.publish.result }}"   # success, failure, or cancelled
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Map status to colour
          case "$STATUS" in
            success)   COLOR=3066993 ;;   # green
            failure)   COLOR=15158332 ;;  # red
            cancelled) COLOR=9807270 ;;   # grey
            *)         COLOR=9807270 ;;
          esac

          # Minimal JSON payload with clickable title and colour
          read -r -d '' PAYLOAD <<EOF
          {
            "embeds": [{
              "title": "${TITLE}",
              "url": "${RUN_URL}",
              "description": "Status: ${STATUS}",
              "color": ${COLOR}
            }]
          }
          EOF

          # Do not fail the job if Discord is unreachable
          curl -sS -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$WEBHOOK_URL" || true
        shell: bash
