name: Notify Discord on Build Completion

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Dummy Publish Job
    runs-on: ubuntu-24.04
    steps:
      - name: Simulate Build
        run: |
          echo "Running simulated build..."
          sleep 3
          echo "Build complete!"

  discord:
    name: Send Discord Notification
    needs: publish
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Post Status to Discord
        run: |
          WEBHOOK_URL="https://discord.com/api/webhooks/1425399520279134249/_tpbIAr_l4c1TVyTTIfCxTt_4RHeYJP8BNEf6Fj9mrG-XREPrThEzPn1-9g4DWiCqtUK"
          TITLE="${{ github.workflow }}"
          STATUS="${{ needs.publish.result }}"

          curl -s -H "Content-Type: application/json" \
            -X POST \
            -d "{\"embeds\":[{\"title\":\"${TITLE}\",\"description\":\"Status: ${STATUS}\"}]}" \
            "$WEBHOOK_URL" || echo "nofail: true"
        shell: bash
